#!/bin/bash
# Railway Quick Deploy Commands
# Copier-coller les commandes nécessaires

echo "════════════════════════════════════════════════════════════"
echo "RAILWAY DEPLOYMENT - QUICK COMMANDS"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "📋 ÉTAPE 1: TEST LOCAL"
echo "────────────────────────────────────────────────────────────"
echo "bash scripts/prepare-railway.sh"
echo ""

echo "📋 ÉTAPE 2: GIT PUSH"
echo "────────────────────────────────────────────────────────────"
echo "git add . && git commit -m 'Prepare for Railway' && git push"
echo ""

echo "📋 ÉTAPE 3: RAILWAY CLI - SETUP"
echo "────────────────────────────────────────────────────────────"
echo "# Installation Railway CLI (une fois)"
echo "npm i -g @railway/cli"
echo ""
echo "# Se connecter"
echo "railway login"
echo ""

echo "📋 ÉTAPE 4: RAILWAY CLI - CRÉER PROJET"
echo "────────────────────────────────────────────────────────────"
echo "# Via le dashboard: https://railway.app/dashboard"
echo "# Ou via CLI:"
echo "railway init"
echo ""

echo "📋 ÉTAPE 5: RAILWAY CLI - CONFIGURER SERVICES"
echo "────────────────────────────────────────────────────────────"
echo "# Ajouter MySQL"
echo "railway add --service mysql"
echo ""

echo "📋 ÉTAPE 6: RAILWAY CLI - VARIABLES"
echo "────────────────────────────────────────────────────────────"
echo "# Générer APP_SECRET"
echo "APP_SECRET=\$(openssl rand -hex 32)"
echo ""
echo "# Définir variables"
echo "railway variables set APP_ENV=prod"
echo "railway variables set APP_DEBUG=0"
echo "railway variables set APP_SECRET=\$APP_SECRET"
echo ""
echo "# Vérifier"
echo "railway variables"
echo ""

echo "📋 ÉTAPE 7: RAILWAY CLI - DEPLOY"
echo "────────────────────────────────────────────────────────────"
echo "# Linkage avec le repo Git"
echo "railway link <PROJECT_ID>"
echo ""
echo "# Ou directement:"
echo "git push railway main"
echo ""

echo "📋 ÉTAPE 8: RAILROAD CLI - MONITORING"
echo "────────────────────────────────────────────────────────────"
echo "# Voir les logs"
echo "railway logs"
echo ""
echo "# Voir le status"
echo "railway status"
echo ""
echo "# Ouvrir l'app dans le navigateur"
echo "railway open"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "✅ DÉPLOIEMENT COMPLET"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "🔗 Dashboard: https://railway.app/dashboard"
echo "📖 Docs: https://docs.railway.app/"
echo ""
